// <auto-generated />
using System;
using GameStoreDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStoreDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212155823_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("GameGenre");

                    b.HasData(
                        new
                        {
                            GamesId = 1,
                            GenresId = 3
                        },
                        new
                        {
                            GamesId = 2,
                            GenresId = 3
                        },
                        new
                        {
                            GamesId = 3,
                            GenresId = 4
                        },
                        new
                        {
                            GamesId = 4,
                            GenresId = 4
                        },
                        new
                        {
                            GamesId = 5,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 6,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 7,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 8,
                            GenresId = 1
                        },
                        new
                        {
                            GamesId = 9,
                            GenresId = 1
                        },
                        new
                        {
                            GamesId = 10,
                            GenresId = 1
                        });
                });

            modelBuilder.Entity("GameStoreDB.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Half-Life",
                            PublisherId = 1,
                            Rating = 9.8000000000000007,
                            ReleaseDate = new DateTime(1998, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Half-Life 2",
                            PublisherId = 1,
                            Rating = 9.9000000000000004,
                            ReleaseDate = new DateTime(2004, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Portal",
                            PublisherId = 1,
                            Rating = 9.5,
                            ReleaseDate = new DateTime(2007, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Portal 2",
                            PublisherId = 1,
                            Rating = 9.6999999999999993,
                            ReleaseDate = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Name = "The Witcher",
                            PublisherId = 2,
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2007, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Name = "The Witcher 2",
                            PublisherId = 2,
                            Rating = 9.1999999999999993,
                            ReleaseDate = new DateTime(2011, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Name = "The Witcher 3",
                            PublisherId = 2,
                            Rating = 9.9000000000000004,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Assassin's Creed",
                            PublisherId = 3,
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(2007, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Far Cry 3",
                            PublisherId = 3,
                            Rating = 9.0999999999999996,
                            ReleaseDate = new DateTime(2012, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Watch Dogs",
                            PublisherId = 3,
                            Rating = 8.1999999999999993,
                            ReleaseDate = new DateTime(2014, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GameStoreDB.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("GameStoreDB.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            Country = "USA",
                            Email = "info@valve.com",
                            Name = "Valve"
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            Country = "Poland",
                            Email = "contact@cdprojekt.com",
                            Name = "CD Projekt"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            Country = "France",
                            Email = "support@ubisoft.com",
                            Name = "Ubisoft"
                        });
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("GameStoreDB.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStoreDB.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStoreDB.Entities.Game", b =>
                {
                    b.HasOne("GameStoreDB.Entities.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });
#pragma warning restore 612, 618
        }
    }
}
