// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyballDB;

#nullable disable

namespace VolleyballDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208185032_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VolleyballDB.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TeamAwayId")
                        .HasColumnType("int");

                    b.Property<int>("TeamHomeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamAwayId");

                    b.HasIndex("TeamHomeId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Team1Score = 3,
                            Team2Score = 1,
                            TeamAwayId = 8,
                            TeamHomeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Team1Score = 2,
                            Team2Score = 3,
                            TeamAwayId = 7,
                            TeamHomeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Team1Score = 3,
                            Team2Score = 0,
                            TeamAwayId = 6,
                            TeamHomeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Team1Score = 1,
                            Team2Score = 3,
                            TeamAwayId = 5,
                            TeamHomeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Team1Score = 3,
                            Team2Score = 2,
                            TeamAwayId = 7,
                            TeamHomeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Team1Score = 0,
                            Team2Score = 3,
                            TeamAwayId = 6,
                            TeamHomeId = 8
                        },
                        new
                        {
                            Id = 7,
                            Team1Score = 3,
                            Team2Score = 1,
                            TeamAwayId = 5,
                            TeamHomeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Team1Score = 2,
                            Team2Score = 3,
                            TeamAwayId = 4,
                            TeamHomeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Team1Score = 1,
                            Team2Score = 3,
                            TeamAwayId = 6,
                            TeamHomeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Team1Score = 3,
                            Team2Score = 0,
                            TeamAwayId = 5,
                            TeamHomeId = 7
                        },
                        new
                        {
                            Id = 11,
                            Team1Score = 2,
                            Team2Score = 3,
                            TeamAwayId = 4,
                            TeamHomeId = 8
                        },
                        new
                        {
                            Id = 12,
                            Team1Score = 0,
                            Team2Score = 3,
                            TeamAwayId = 3,
                            TeamHomeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Team1Score = 3,
                            Team2Score = 0,
                            TeamAwayId = 5,
                            TeamHomeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Team1Score = 3,
                            Team2Score = 1,
                            TeamAwayId = 4,
                            TeamHomeId = 6
                        },
                        new
                        {
                            Id = 15,
                            Team1Score = 2,
                            Team2Score = 3,
                            TeamAwayId = 3,
                            TeamHomeId = 7
                        },
                        new
                        {
                            Id = 16,
                            Team1Score = 3,
                            Team2Score = 2,
                            TeamAwayId = 2,
                            TeamHomeId = 8
                        },
                        new
                        {
                            Id = 17,
                            Team1Score = 2,
                            Team2Score = 3,
                            TeamAwayId = 4,
                            TeamHomeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Team1Score = 3,
                            Team2Score = 1,
                            TeamAwayId = 3,
                            TeamHomeId = 5
                        },
                        new
                        {
                            Id = 19,
                            Team1Score = 2,
                            Team2Score = 3,
                            TeamAwayId = 2,
                            TeamHomeId = 6
                        },
                        new
                        {
                            Id = 20,
                            Team1Score = 3,
                            Team2Score = 0,
                            TeamAwayId = 8,
                            TeamHomeId = 7
                        });
                });

            modelBuilder.Entity("VolleyballDB.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "E"
                        },
                        new
                        {
                            Id = 6,
                            Name = "F"
                        },
                        new
                        {
                            Id = 7,
                            Name = "G"
                        },
                        new
                        {
                            Id = 8,
                            Name = "H"
                        });
                });

            modelBuilder.Entity("VolleyballDB.Entities.Game", b =>
                {
                    b.HasOne("VolleyballDB.Entities.Team", "TeamAway")
                        .WithMany("AwayGames")
                        .HasForeignKey("TeamAwayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballDB.Entities.Team", "TeamHome")
                        .WithMany("HomeGames")
                        .HasForeignKey("TeamHomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamAway");

                    b.Navigation("TeamHome");
                });

            modelBuilder.Entity("VolleyballDB.Entities.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");
                });
#pragma warning restore 612, 618
        }
    }
}
